---
driver:
  name: docker

provisioner:
  name: chef_extended_attributes
  nodes_path: 'test/nodes'
  cookbooks_path: 'test/cookbooks'

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - 'recipe[extended_attributes_test::default]'
    attributes:
      valuefromkitchen: true
  - name: kitchenmerged
    run_list:
      - 'recipe[extended_attributes_test::kitchenmerged]'
    attributes:
      valuefromdna: 'overridden'
  - name: kitchenoverride
    provisioner:
      merge_attributes: false
    attributes:
      valuefromkitchen: 'shouldnevershowup'
  - name: clearingattributes
    run_list:
      - 'recipe[extended_attributes_test::clearingattributes]'
